#!/usr/bin/python

import sys
from Bio import SeqIO

def main(cmd): {
    "search-fasta-naive" : lambda : searchFastaNaive(sys.argv[2], sys.argv[3]),
    "suffix-array" : lambda : suffixArray(sys.argv[2])
}[cmd]()

def suffixArray(g):
    l = []
    gh = open(g, "r")
    g = list(SeqIO.parse(gh, "fasta"))[0].seq
    gh.close()
    gn = len(g)
    for i in range(gn) :
        l.append((i, g[i:gn]))
    print " ".join(map(
        lambda c : str(c[0]), 
        sorted(l, key=lambda c : c[1])
    ))

def searchFastaNaive(g, r):
    gh = open(g, "r")
    g = list(SeqIO.parse(gh, "fasta"))[0].seq
    gh.close()
    gn = len(g)
    rn = len(r)
    for i in range(gn) :
        if g[i:i+rn] == r :
            sys.stdout.write(str(i) + " ")

main(sys.argv[1])
